version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "This is a build step"    # similar to "script" in GitLab

  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "This is a test step"

  bundler-audit:
    machine: true
    docker:
      - image: docker:dind
    steps:
      - checkout

      - run: 
          command: docker run --rm -v $(pwd):/src -v /var/run/docker.sock:/var/run/docker.sock -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json
          when: always

      - store_artifacts:
          path: bundle-audit-output.json
          destination: bundler-audit-artifact
          when: always

  integration:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  rails:
    jobs:
      - build
      - test:
          requires:
            - build 
      - bundler-audit:
          requires:
            - test
      - integration:
          requires:
            - bundler-audit
      - prod:
          type: approval
          requires:
            - integration
